In [1]:
import matplotlib.pyplot as plt
import pickle

from pmbrl.model2 import Model, Triplet_Loss_Normalized
from pmbrl.data import Experiment_Data, get_data_expanded

# Training

In [2]:
data = Experiment_Data()

# data.load(path='../training_data_short.csv')
data.load(path='../training_data.csv')
data.build_training_dataset()

,step,episode,p,s,a,r,s_,a_,r_,s__
573,1,22,"(0.1859246409325834, 0.509421113235871)","(-0.014, 0.166, -0.041, -0.304)",0,1.0,"(-0.011, -0.029, -0.047, -0.012)",1.0,1.0,"(-0.011, 0.168, -0.047, -0.333)"
284,0,10,"(0.0746887501825485, 0.1350490291932765)","(0.046, -0.029, 0.033, -0.035)",1,1.0,"(0.045, 0.199, 0.032, -1.061)",1.0,1.0,"(0.049, 0.428, 0.011, -2.087)"
1312,34,53,"(0.2444473003074412, 0.4846825463128728)","(-0.007, 0.029, -0.022, -0.114)",1,1.0,"(-0.006, 0.227, -0.024, -0.46)",1.0,1.0,"(-0.002, 0.424, -0.033, -0.806)"
2173,24,84,"(0.0433876892251688, 0.5641318888962644)","(0.009, 0.021, 0.14, 0.454)",1,1.0,"(0.009, 0.213, 0.149, 0.245)",0.0,1.0,"(0.014, 0.018, 0.154, 0.531)"
1098,9,45,"(0.0966014343877297, 0.3641500656519551)","(0.047, 0.601, -0.04, -1.118)",1,1.0,"(0.059, 0.801, -0.062, -1.536)",1.0,1.0,"(0.075, 1.002, -0.093, -1.963)"
...,...,...,...,...,...,...,...,...,...,...
2475,9,97,"(0.1358594884350926, 0.7069625486901497)","(-0.014, -0.582, 0.046, 0.709)",0,1.0,"(-0.026, -0.774, 0.06, 0.932)",0.0,1.0,"(-0.042, -0.966, 0.078, 1.158)"
1234,27,50,"(0.3156324259991037, 0.4950654122165437)","(0.103, -0.128, -0.176, -0.405)",0,1.0,"(0.101, -0.323, -0.184, -0.128)",1.0,1.0,"(0.094, -0.122, -0.187, -0.539)"
2319,6,92,"(0.1771043759930183, 0.8300521931250568)","(0.001, -0.042, -0.014, -0.034)",0,1.0,"(0.0, -0.232, -0.015, 0.15)",1.0,1.0,"(-0.004, -0.041, -0.012, -0.04)"
1607,29,65,"(0.1785778102029531, 1.438381745613701)","(0.092, 0.57, -0.136, -0.53)",1,1.0,"(0.103, 0.757, -0.147, -0.653)",1.0,1.0,"(0.118, 0.945, -0.16, -0.776)"
1800,5,71,"(0.101516037315209, 0.2595372644863228)","(-0.058, -0.211, 0.122, 0.732)",1,1.0,"(-0.062, -0.008, 0.136, 0.246)",1.0,1.0,"(-0.062, 0.196, 0.141, -0.23)"

In [3]:
model = Model(transition_criterion_clss=Triplet_Loss_Normalized)

loss_param=1e-5

x, y = model.get_features_targets(data.training_dataset)
y

tensor([[-0.0110,  0.1680, -0.0470,  ...,  0.5094,  0.1524,  0.5191],
        [ 0.0490,  0.4280,  0.0110,  ...,  0.1350,  0.1450,  0.4437],
        [-0.0020,  0.4240, -0.0330,  ...,  0.4847,  0.0434,  0.5641],
        ...,
        [-0.0040, -0.0410, -0.0120,  ...,  0.8301,  0.1450,  0.4437],
        [ 0.1180,  0.9450, -0.1600,  ...,  1.4384,  0.2444,  0.4847],
        [-0.0620,  0.1960,  0.1410,  ...,  0.2595,  0.1632,  0.2848]])

In [4]:
trainer = model.train(x, y, num_epochs=3000, margin=.1)
train_data = data.get_training_data(trainer, inference_schema=model.inference_schema)
train_data.head()

,epoch,triplet,mse_s,transition,reward
0,0,0.245802,"[0.003684100229293108, 0.016939280554652214, 0...",0.995784,1.788927
1,1,0.245872,"[0.003577902214601636, 0.016869548708200455, 0...",0.964384,1.785399
2,2,0.245942,"[0.0034768981859087944, 0.016800185665488243, ...",0.933794,1.781919
3,3,0.246010,"[0.003381120041012764, 0.01673116721212864, 0....",0.904009,1.778484
4,4,0.246077,"[0.0032905987463891506, 0.0166624803096056, 0....",0.875026,1.775088

In [5]:

features = {
    "x": x,
    "y": y 
}

nome_do_arquivo = 'features.pkl'
with open(nome_do_arquivo, 'wb') as arquivo:
    pickle.dump(features, arquivo)

In [ ]:
del x
del y
del features

with open(nome_do_arquivo, 'rb') as arquivo:
    features = pickle.load(arquivo)
    x, y = features.values()

y

tensor([[-0.0110,  0.1680, -0.0470,  ...,  0.5094,  0.1524,  0.5191],
        [ 0.0490,  0.4280,  0.0110,  ...,  0.1350,  0.1450,  0.4437],
        [-0.0020,  0.4240, -0.0330,  ...,  0.4847,  0.0434,  0.5641],
        ...,
        [-0.0040, -0.0410, -0.0120,  ...,  0.8301,  0.1450,  0.4437],
        [ 0.1180,  0.9450, -0.1600,  ...,  1.4384,  0.2444,  0.4847],
        [-0.0620,  0.1960,  0.1410,  ...,  0.2595,  0.1632,  0.2848]])

In [7]:
trainer = model.train(x, y, num_epochs=3000, margin=.1)
train_data = data.get_training_data(trainer, inference_schema=model.inference_schema)
train_data.head()

,epoch,triplet,mse_s,transition,reward
0,0,0.043788,"[2.0743857021443546e-05, 3.8776834117015824e-0...",0.044145,0.000294
1,1,0.043784,"[2.0741008484037593e-05, 3.877906783600338e-05...",0.044141,0.000293
2,2,0.043780,"[2.0718598534585908e-05, 3.876690607285127e-05...",0.044137,0.000292
3,3,0.043773,"[2.0705203496618196e-05, 3.8741305615985766e-0...",0.044130,0.000290
4,4,0.043771,"[2.0706458599306643e-05, 3.870858927257359e-05...",0.044128,0.000289