In [1]:
import matplotlib.pyplot as plt
import pickle

from pmbrl.model2 import Model
from pmbrl.data import Experiment_Data, get_data_expanded

In [2]:
nome_do_arquivo = 'regular_normilized.pkl'

with open(nome_do_arquivo, 'rb') as arquivo:
    exp = pickle.load(arquivo)
    data = exp['data']
    model = exp['model']

del exp
del arquivo

In [3]:
data.evaluate_model(model, path='../testing_data.csv')
results = data.get_evaluation_metrics()
results.head()

,step,episode,p,s,a,r,s_,a_,r_,s__,...,rse_s1,rse_s2,rse_s3,rse_r,rse_s0_normalized,rse_s1_normalized,rse_s2_normalized,rse_s3_normalized,rse,rse_normalized
0,0,0,"(0.5280280669895349, 0.1691488904272192)","(-0.018, -0.046, 0.013, -0.019)",0,1.0,"(-0.019, -0.285, 0.013, 1.258)",0.0,1.0,"(-0.025, -0.525, 0.038, 2.534)",...,0.041,0.003,0.901,0.0,0.546990,0.536136,0.508393,0.511765,0.946,0.525821
1,1,0,"(0.5280280669895349, 0.1691488904272192)","(-0.019, -0.285, 0.013, 1.258)",0,1.0,"(-0.025, -0.525, 0.038, 2.534)",1.0,1.0,"(-0.035, -0.288, 0.088, 1.326)",...,0.067,0.007,1.008,0.0,0.548046,0.542527,0.517986,0.520921,1.084,0.532370
2,2,0,"(0.5280280669895349, 0.1691488904272192)","(-0.025, -0.525, 0.038, 2.534)",1,1.0,"(-0.035, -0.288, 0.088, 1.326)",0.0,1.0,"(-0.041, -0.532, 0.115, 2.694)",...,0.041,0.003,0.968,0.0,0.550158,0.536136,0.508393,0.517498,1.016,0.528046
3,3,0,"(0.5280280669895349, 0.1691488904272192)","(-0.035, -0.288, 0.088, 1.326)",0,1.0,"(-0.041, -0.532, 0.115, 2.694)",1.0,1.0,"(-0.052, -0.3, 0.169, 1.601)",...,0.052,0.001,0.917,0.0,0.552270,0.538840,0.503597,0.513134,0.976,0.526960
4,4,0,"(0.5280280669895349, 0.1691488904272192)","(-0.041, -0.532, 0.115, 2.694)",1,1.0,"(-0.052, -0.3, 0.169, 1.601)",0.0,1.0,"(-0.058, -0.546, 0.201, 3.045)",...,0.042,0.002,1.012,0.0,0.555438,0.536382,0.505995,0.521263,1.065,0.529769

In [6]:
results[['rse', 'rse_normalized', 
       'rse_s0', 'rse_s1', 'rse_s2', 'rse_s3', 'rse_r', 'rse_s0_normalized',
       'rse_s1_normalized', 'rse_s2_normalized', 'rse_s3_normalized']].describe()

,rse,rse_normalized,rse_s0,rse_s1,rse_s2,rse_s3,rse_r,rse_s0_normalized,rse_s1_normalized,rse_s2_normalized,rse_s3_normalized
count,2127.000000,2127.000000,2127.000000,2127.000000,2127.000000,2127.000000,2127.0,2127.000000,2127.000000,2127.000000,2127.000000
mean,0.192357,0.507811,0.002819,0.014575,0.000800,0.174162,0.0,0.548912,0.529640,0.503118,0.449573
std,0.220381,0.005796,0.003585,0.014559,0.001634,0.211500,0.0,0.003786,0.003579,0.003918,0.018097
min,0.003000,0.502201,0.000000,0.000000,0.000000,0.000000,0.0,0.545935,0.526057,0.501199,0.434671
25%,0.081000,0.504842,0.001000,0.005000,0.000000,0.065000,0.0,0.546990,0.527286,0.501199,0.440233
50%,0.132000,0.506382,0.002000,0.011000,0.001000,0.117000,0.0,0.548046,0.528761,0.503597,0.444682
75%,0.219000,0.508445,0.003000,0.019000,0.001000,0.197500,0.0,0.549102,0.530728,0.503597,0.451570
max,2.266000,0.566403,0.034000,0.152000,0.042000,2.129000,0.0,0.581837,0.563422,0.601918,0.616839

In [4]:
expansions = {
    'estimated_p': ['p0', 'p1'],
    's_': ['s0', 's1', 's2', 's3'],
    's__': ['s_0', 's_1', 's_2', 's_3'],
}


df = data.evaluation_data[data.evaluation_data['episode'] == 98].copy().reset_index(drop=True)
df = get_data_expanded(df, expansions)
df.head()

,step,episode,p,s,a,r,s_,a_,r_,s__,...,p0,p1,s0,s1,s2,s3,s_0,s_1,s_2,s_3
0,0,98,"(0.1955406148449595, 0.6245501454716056)","(0.044, 0.035, -0.043, -0.021)",1,1.0,"(0.045, 0.229, -0.043, -0.284)",0.0,1.0,"(0.05, 0.036, -0.049, -0.044)",...,-0.154,0.149,0.045,0.229,-0.043,-0.284,0.050,0.036,-0.049,-0.044
1,1,98,"(0.1955406148449595, 0.6245501454716056)","(0.045, 0.229, -0.043, -0.284)",0,1.0,"(0.05, 0.036, -0.049, -0.044)",0.0,1.0,"(0.05, -0.156, -0.05, 0.194)",...,-0.177,0.110,0.050,0.036,-0.049,-0.044,0.050,-0.156,-0.050,0.194
2,2,98,"(0.1955406148449595, 0.6245501454716056)","(0.05, 0.036, -0.049, -0.044)",0,1.0,"(0.05, -0.156, -0.05, 0.194)",0.0,1.0,"(0.047, -0.349, -0.046, 0.432)",...,-0.194,0.077,0.050,-0.156,-0.050,0.194,0.047,-0.349,-0.046,0.432
3,3,98,"(0.1955406148449595, 0.6245501454716056)","(0.05, -0.156, -0.05, 0.194)",0,1.0,"(0.047, -0.349, -0.046, 0.432)",1.0,1.0,"(0.04, -0.155, -0.037, 0.168)",...,-0.205,0.051,0.047,-0.349,-0.046,0.432,0.040,-0.155,-0.037,0.168
4,4,98,"(0.1955406148449595, 0.6245501454716056)","(0.047, -0.349, -0.046, 0.432)",1,1.0,"(0.04, -0.155, -0.037, 0.168)",0.0,1.0,"(0.037, -0.348, -0.034, 0.41)",...,-0.179,0.093,0.040,-0.155,-0.037,0.168,0.037,-0.348,-0.034,0.410

In [7]:
del data
del model