In [1]:
import matplotlib.pyplot as plt
import pickle

from pmbrl.model2 import Model
from pmbrl.data import Experiment_Data, get_data_expanded

In [2]:
nome_do_arquivo = 'triplet.pkl'

with open(nome_do_arquivo, 'rb') as arquivo:
    exp = pickle.load(arquivo)
    data = exp['data']
    model = exp['model']

del exp
del arquivo

In [3]:
data.evaluate_model(model, path='../testing_data.csv')
results = data.get_evaluation_metrics()
results.head()

,step,episode,p,s,a,r,s_,a_,r_,s__,...,rse_s1,rse_s2,rse_s3,rse_r,rse_s0_normalized,rse_s1_normalized,rse_s2_normalized,rse_s3_normalized,rse,rse_normalized
0,0,0,"(0.5280280669895349, 0.1691488904272192)","(-0.018, -0.046, 0.013, -0.019)",0,1.0,"(-0.019, -0.285, 0.013, 1.258)",0.0,1.0,"(-0.025, -0.525, 0.038, 2.534)",...,0.014,0.022,0.168,0.0,0.550158,0.529499,0.553957,0.449046,0.208,0.520665
1,1,0,"(0.5280280669895349, 0.1691488904272192)","(-0.019, -0.285, 0.013, 1.258)",0,1.0,"(-0.025, -0.525, 0.038, 2.534)",1.0,1.0,"(-0.035, -0.288, 0.088, 1.326)",...,0.050,0.022,0.121,0.0,0.565998,0.538348,0.553957,0.445024,0.212,0.525832
2,2,0,"(0.5280280669895349, 0.1691488904272192)","(-0.025, -0.525, 0.038, 2.534)",1,1.0,"(-0.035, -0.288, 0.088, 1.326)",0.0,1.0,"(-0.041, -0.532, 0.115, 2.694)",...,0.000,0.020,0.194,0.0,0.552270,0.526057,0.549161,0.451271,0.220,0.519690
3,3,0,"(0.5280280669895349, 0.1691488904272192)","(-0.035, -0.288, 0.088, 1.326)",0,1.0,"(-0.041, -0.532, 0.115, 2.694)",1.0,1.0,"(-0.052, -0.3, 0.169, 1.601)",...,0.030,0.007,0.045,0.0,0.561774,0.533432,0.517986,0.438521,0.097,0.512928
4,4,0,"(0.5280280669895349, 0.1691488904272192)","(-0.041, -0.532, 0.115, 2.694)",1,1.0,"(-0.052, -0.3, 0.169, 1.601)",0.0,1.0,"(-0.058, -0.546, 0.201, 3.045)",...,0.003,0.017,0.055,0.0,0.549102,0.526794,0.541966,0.439377,0.078,0.514310

In [4]:
results[['rse', 'rse_normalized', 
       'rse_s0', 'rse_s1', 'rse_s2', 'rse_s3', 'rse_r', 'rse_s0_normalized',
       'rse_s1_normalized', 'rse_s2_normalized', 'rse_s3_normalized']].describe()

,rse,rse_normalized,rse_s0,rse_s1,rse_s2,rse_s3,rse_r,rse_s0_normalized,rse_s1_normalized,rse_s2_normalized,rse_s3_normalized
count,2127.000000,2127.000000,2127.000000,2127.000000,2127.000000,2127.000000,2127.0,2127.000000,2127.000000,2127.000000,2127.000000
mean,0.047653,0.508197,0.007160,0.010738,0.005267,0.024488,0.0,0.553496,0.528697,0.513829,0.436766
std,0.051139,0.005134,0.008085,0.014691,0.004853,0.036386,0.0,0.008537,0.003611,0.011638,0.003113
min,0.003000,0.502401,0.000000,0.000000,0.000000,0.000000,0.0,0.545935,0.526057,0.501199,0.434671
25%,0.021000,0.505214,0.002000,0.003000,0.002000,0.007000,0.0,0.548046,0.526794,0.505995,0.435270
50%,0.033000,0.507033,0.005000,0.006000,0.004000,0.014000,0.0,0.551214,0.527532,0.510791,0.435869
75%,0.056000,0.509357,0.010000,0.012000,0.007000,0.028000,0.0,0.556494,0.529007,0.517986,0.437067
max,0.542000,0.566119,0.120000,0.189000,0.058000,0.388000,0.0,0.672650,0.572517,0.640288,0.467870

In [5]:
del data
del model